name: buildCI

on:
  push:
    branches: [ main, singleproject ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

env:
    DOTNETVERSION: 8.0.100-rc.2.23502.2

jobs:
  buildMauiLib:
    runs-on: macos-13
    
    steps:
      - uses: actions/checkout@v2

      # - name: Setup .NET SDK ${{env.DOTNETVERSION}}
      #   uses: actions/setup-dotnet@v1
      #   with:
      #     dotnet-version:  '${{env.DOTNETVERSION}}'


      - name: Install .NET 8
        shell: bash
        run: |
          curl -o dotnet-install.sh -sSL https://dotnet.microsoft.com/download/dotnet/scripts/v1/dotnet-install.sh
          sh dotnet-install.sh --version ${{env.DOTNETVERSION}}
          dotnet --list-sdks  

      - name: List installed .NET info
        shell: pwsh
        run: dotnet --info

      - name: Install .NET MAUI
        shell: bash
        run: |
          dotnet workload install android ios maui
    
      - name: Restore nuget packages
        run: |
          dotnet restore MobCAT.Maui.sln

      - name: Build and Pack Library
        run: |
          cd MobCAT
          dotnet pack MobCAT.csproj -c Release

      - uses: actions/upload-artifact@v2
        with:
          name: artifacts-nuget
          path: |
            **/*.nupkg
